#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, in6,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  rightIME,       sensorNone)
#pragma config(Sensor, I2C_2,  leftIME,        sensorNone)
#pragma config(Sensor, I2C_3,  armIME,         sensorNone)
#pragma config(Motor,  port3,           leftwheel,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           rightwheel,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           liftlift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftbottommotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lefttopmotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightbottommotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           toprightmotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while(1 == 1)

{
		motor [leftwheel] = vexRT[Ch3];
		motor [rightwheel] = vexRT[Ch2];



		if(vexRT[Btn6U] == 1)
	{
		motor[leftbottommotor] = -40;
		motor[lefttopmotor] = -40;
		motor[rightbottommotor] = 40;
		motor[toprightmotor] = 40;
	}

		else if(vexRT[Btn6D] == 1)
{
		motor[lefttopmotor] = 40;
		motor[leftbottommotor] = 40;
		motor[rightbottommotor] = -40;
		motor[toprightmotor] = -40;
	}

		else
	{
		motor[lefttopmotor] = 0;
			motor[leftbottommotor] = 0;
			motor[rightbottommotor] = 0;
			motor[toprightmotor] = 0;
		}

			if(vexRT[Btn5U] == 1)
	{
		motor[liftlift] = -127;

	}

		else if(vexRT[Btn5D] == 1)
{
		motor[liftlift] = 127;

	}

		else
	{
		motor[liftlift] = 0;

		}












	}
}
