#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(vexRT [ Btn7D] == 0)  // start command with button pressed to zero
	{
	}

	clearTimer (T1);
	while(time1 [T1] < 60000)// Wait time command

{
		motor [leftMotor] = vexRT[Ch3];
		motor [rightMotor] = vexRT[Ch2];


	}
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}
