#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, in6,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, TopEncoder,     sensorRotation)
#pragma config(Sensor, I2C_1,  rightIME,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armIME,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port6,           armMotor,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(2000);                        // Move forward

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(SensorValue[leftEncoder] < 1000)
{
	motor [rightMotor] = 63;
	motor [leftMotor] = 63;}


SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;					//Move Backwards

	while(SensorValue[leftEncoder] > -1000)
{
	motor [rightMotor] = -63;
	motor [leftMotor] = -63;}

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(SensorValue[leftEncoder] < 2000)
{
	motor [rightMotor] = 63;
	motor [leftMotor] = 63;}


SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;					//Move Backwards

	while(SensorValue[leftEncoder] > -2000)
{
	motor [rightMotor] = -63;
	motor [leftMotor] = -63;}


		SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(SensorValue[leftEncoder] < 3000)
{
	motor [rightMotor] = 63;
	motor [leftMotor] = 63;}


SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;					//Move Backwards

	while(SensorValue[leftEncoder] > -3000)
{
	motor [rightMotor] = -63;
	motor [leftMotor] = -63;}
}
