#pragma config(StandardModel, "RVW SWERVEBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//Threshold Value, Dark
//Left = 4096
//Center = 4096
//Right = 4096
//451
//451
//451
// Threshold = (Avg Light + Avg Dark) / 2
// = (451 + 4096) / 2 = 2274

int threshold = 550;

while(true)
{

  if(SensorValue(rightLineFollower) > threshold)
    {
      // counter-steer right:
      motor[leftMotor]  = 88;
      motor[rightMotor] = 20;
    }
    // CENTER sensor sees dark:
    if(SensorValue(centerLineFollower) > threshold)
    {
      // go straight
      motor[leftMotor]  = 44;
      motor[rightMotor] = 44;
    }
    // LEFT sensor sees dark:
    if(SensorValue(leftLineFollower) > threshold)
    {
      // counter-steer left:
      motor[leftMotor]  = 200;
      motor[rightMotor] = 88;
    }
  }
}
