#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    armPot,         sensorAnalog)
#pragma config(Sensor, in4,    ,               sensorGyro)
#pragma config(Sensor, in6,    ,               sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  frontLimit,     sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, TopEncoder,     sensorRotation)
#pragma config(Sensor, I2C_1,  rightIME,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armIME,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port6,           armMotor,      tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma debuggerWindows("joystickSimple");
#include "JoystickDriver.c"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turnpointleft (int encoderCount) // Parameters control the Number value or what have you of what you want to run in your robot task main with your fuction
{																				// Fuctions start with void then what ever you want to name it then ()
	int normalSpeed;					// Create the Varible Here   Varibles run within a fuction or task Main that act like a mini fuction
	int slowSpeed;																			// Varibles give a item a value or phase that can be used in programs as a substitue
	normalSpeed = 40;					// Initailize te Varible
	slowSpeed = 35;

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;


	while(SensorValue[rightEncoder] < encoderCount)      // Turn Left jbflot@nrec.ri.cmu.edu
	{
		motor [rightMotor] = 40;
		motor [leftMotor] = -40;
		}

	if(SensorValue[leftEncoder] > SensorValue[rightEncoder])
	{
		motor[rightMotor] = normalSpeed;
		motor[leftMotor] = slowSpeed;
	}
	if( SensorValue [rightEncoder] > SensorValue[leftEncoder])
	{
		motor[rightMotor] = slowSpeed;
		motor[leftMotor] = normalSpeed;
	}
	if( SensorValue[leftEncoder] == SensorValue[rightEncoder])
	{
		motor [rightMotor] = normalSpeed;
		motor [leftMotor] = normalSpeed;
	}
motor [rightMotor] = 0;
		motor [leftMotor] = 0;
}





void turnpointright(int encoderCount)
{
	int normalSpeed;					// Create the Varible Here
	int slowSpeed;
	normalSpeed = 40;					// Initailize te Varible
	slowSpeed = 35;

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;


	while(SensorValue[leftEncoder] < encoderCount)    //Turn Right
	{

		motor [rightMotor] = -40;
		motor [leftMotor] = 40;
		}

	if(SensorValue[leftEncoder] > SensorValue[rightEncoder])
	{
		motor[rightMotor] = normalSpeed;
		motor[leftMotor] = slowSpeed;
	}
	if( SensorValue [rightEncoder] > SensorValue[leftEncoder])
	{
		motor[rightMotor] = slowSpeed;
		motor[leftMotor] = normalSpeed;
	}
	if( SensorValue[leftEncoder] == SensorValue[rightEncoder])
	{
		motor [rightMotor] = normalSpeed;
		motor [leftMotor] = normalSpeed;
	}
motor [rightMotor] = 0;
		motor [leftMotor] = 0;
}



void movestraight(int encoderCount)
{



	int normalSpeed;					// Create the Varible Here
	int slowSpeed;
	normalSpeed = 40;					// Initailize te Varible
	slowSpeed = 25;

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(SensorValue[leftEncoder] < encoderCount)
	{
		motor [rightMotor] = 40;
		motor [leftMotor] = 40;
		}

	if(SensorValue[leftEncoder] > SensorValue[rightEncoder])
	{
		motor[rightMotor] = normalSpeed;
		motor[leftMotor] = slowSpeed;
	}
	if( SensorValue [rightEncoder] > SensorValue[leftEncoder])
	{
		motor[rightMotor] = slowSpeed;
		motor[leftMotor] = normalSpeed;
	}
	if( SensorValue[leftEncoder] == SensorValue[rightEncoder])
	{
		motor [rightMotor] = normalSpeed;
		motor [leftMotor] = normalSpeed;
	}
	motor [rightMotor] = 0;
		motor [leftMotor] = 0;
}


void movebackward(int encoderCount)
{



	int normalSpeed;					// Create the Varible Here
	int slowSpeed;
	normalSpeed = -40;					// Initailize te Varible
	slowSpeed = -25;

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(SensorValue[leftEncoder] > encoderCount)
	{
		motor [rightMotor] = -40;
		motor [leftMotor] = -40;
		}

	if(SensorValue[leftEncoder] > SensorValue[rightEncoder])
	{
		motor[rightMotor] = normalSpeed;
		motor[leftMotor] = slowSpeed;
	}
	if( SensorValue [rightEncoder] > SensorValue[leftEncoder])
	{
		motor[rightMotor] = slowSpeed;
		motor[leftMotor] = normalSpeed;
	}
	if( SensorValue[leftEncoder] == SensorValue[rightEncoder])
	{
		motor [rightMotor] = normalSpeed;
		motor [leftMotor] = normalSpeed;
	}
	motor [rightMotor] = 0;
		motor [leftMotor] = 0;
}



void Armup()
{
motor [ armMotor] = 30;
wait1Msec(2000);
motor [armMotor] = 0;

}

void armDown()
{
motor [ armMotor] = -30;
wait1Msec(2000);
motor [armMotor] = 0;

}






task main()
{

wait1Msec (2000);
	{
	}

	/* clearTimer (T1);
	while(time1 [T1] < 20000)// Wait time command


{




	movestraight(500);


 Armup();


	 movebackward (-400);

	turnpointleft (370);

	movestraight(850);

	turnpointright (370);

armDown();
}
*/

clearTimer (T1);
	while(time1 [T1] < 100000)// Wait time command

{
 //Integer variable that allows you to specify a "deadzone" where values (both positive or negative)
  //less than the threshold will be ignored.
  int threshold = 10;

  //Loop Forever
  while(1 == 1)
  {
    //Get the Latest joystick values
    getJoystickSettings(joystick);

    if(abs(joystick.joy1_y2) > threshold)     // If the right analog stick's Y-axis readings are either above or below the threshold...
    {
      motor[rightMotor] = joystick.joy1_y2;   // ...the right motor is assigned a power level equal to the right analog stick's Y-axis reading.
    }
    else                                      // Else the readings are within the threshold, so
    {
      motor[rightMotor] = 0;                  // ...the right motor is stopped with a power level of 0.
    }


    if(abs(joystick.btn_RB6) = 1)     // If the left analog stick's Y-axis readings are either above or below the threshold...
    {
      motor[armMotor] = joystick.btn_RB6;    // ...the left motor is assigned a power level equal to the left analog stick's Y-axis reading.
    }
    else                                      // Else if the readings are within the threshold...
    {
      motor[armMotor] = 0;                   // ...the left motor is stopped with a power level of 0.
    }

    if(abs(joystick.tri_RT6) = 1)     // If the left analog stick's Y-axis readings are either above or below the threshold...
    {
      motor[armMotor] = joystick.tri_RT6;    // ...the left motor is assigned a power level equal to the left analog stick's Y-axis reading.
    }
    else                                      // Else if the readings are within the threshold...
    {
      motor[armMotor] = 0;                   // ...the left motor is stopped with a power level of 0.
    }

}}
