#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[port2] = 96;     //Forward
motor[port3] = 96;
wait1Msec (6000);

motor[port2] = 96;      // Left swing turn
motor[port3] = 0;
wait1Msec (1655);

motor[port2] = 96;     //Forward
motor[port3] = 96;
wait1Msec (6000);

motor[port2] = 96;      // Left swing turn
motor[port3] = 0;
wait1Msec (1655);


motor[port2] = 96;     //Forward
motor[port3] = 96;
wait1Msec (6000);

motor[port2] = 96;      // Left swing turn
motor[port3] = 0;
wait1Msec (1655);

motor[port2] = 96;     //Forward
motor[port3] = 96;
wait1Msec (6000);




motor[port2] = 96;     //Forward
motor[port3] = 96;
wait1Msec (6000);

motor[port2] = 96;      // Left turn point
motor[port3] = -96;
wait1Msec (850);

motor[port2] = 96;     //Forward
motor[port3] = 96;
wait1Msec (6000);

motor[port2] = 96;      // Left turn point
motor[port3] = -96;
wait1Msec (850);

motor[port2] = 96;     //Forward
motor[port3] = 96;
wait1Msec (6000);

motor[port2] = 96;      // Left turn point
motor[port3] = -96;
wait1Msec (850);

motor[port2] = 96;     //Forward
motor[port3] = 96;
wait1Msec (6000);

motor[port2] = 96;      // Left turn point
motor[port3] = -96;
wait1Msec (850);
}
