#pragma config(Motor,  port1,           arm,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[arm] = 63;
	wait1Msec(2000);
	motor[arm] = -63;
	wait1Msec(2000);
}
