#pragma config(Motor,  port1,           LeftWheels,    tmotorVex269_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           Arm1,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           Arm2,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           Arm3,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           Claw,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          RightWheels,   tmotorVex269_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[port1] = 127;
	motor[port10] = 127;
	wait1Msec(10000);
}
