#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftDrive,     tmotorVex393_HBridge, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port2,           liftBottomLeft, tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           liftTopLeft,   tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           liftBottomRight, tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           liftTopRight,  tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          rightDrive,    tmotorVex393_HBridge, openLoop, reversed, driveRight, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

task handleLifter()
{
	while (true)
	{
		bool shouldLift = vexRT[Btn6U] == 1;
		bool shouldLower = vexRT[Btn6D] == 1;
		if (shouldLift)
		{
			motor[liftBottomLeft] = 127;
			motor[liftTopLeft] = 127;
			motor[liftBottomRight] = 127;
			motor[liftTopRight] = 127;
		}
		else if (shouldLower)
		{
			motor[liftBottomLeft] = -127;
			motor[liftTopLeft] = -127;
			motor[liftBottomRight] = -127;
			motor[liftTopRight] = -127;
		}
	}
}

task handleDrive()
{
	while (true)
	{
		motor[leftDrive] = vexRT[Ch3];
		motor[rightDrive] = vexRT[Ch2];
		wait1Msec(50);
	}
}

void pre_auton()
{
}

task autonomous()
{
}

task usercontrol()
{
	startTask(handleLifter);
	startTask(handleDrive);
	while (true)
	{
		wait1Msec(250);
	}
}
