#pragma config(UserModel, "./foxbot_temp_config.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "motor_slew.cpp"

#define MAX_SPEED 127

task handleLifter()
{
	while (true)
	{
		bool shouldLift = vexRT[Btn6U] == 1;
		bool shouldLower = vexRT[Btn6D] == 1;
		if (shouldLift)
		{
			motorRequests[liftBottomLeft] = -127;
			motorRequests[liftTopLeft] = -127;
			motorRequests[liftBottomRight] = -127;
			motorRequests[liftTopRight] = -127;
		}
		else if (shouldLower)
		{
			motorRequests[liftBottomLeft] = 127;
			motorRequests[liftTopLeft] = 127;
			motorRequests[liftBottomRight] = 127;
			motorRequests[liftTopRight] = 127;
		}
		else
		{
			motorRequests[liftBottomLeft] = 0;
			motorRequests[liftTopLeft] = 0;
			motorRequests[liftBottomRight] = 0;
			motorRequests[liftTopRight] = 0;
		}
		wait1Msec(50);
	}
}

void performQuickFlip()
{
	motorRequests[flipper] = MAX_SPEED;
	wait1Msec(400);
	motorRequests[flipper] = -MAX_SPEED;
	wait1Msec(400);
	motorRequests[flipper] = 0;
}

task handleFlipper()
{
	while (true)
	{
		bool shouldFlip = vexRT[Btn8U] == 1;
		if (shouldFlip)
		{
			performQuickFlip();
		}
		else
		{

		}
	}
}

task handleDrive()
{
	while (true)
	{
		motorRequests[leftDrive] = vexRT[Ch3];
		motorRequests[rightDrive] = vexRT[Ch2];
		wait1Msec(50);
	}
}

void pre_auton()
{
}

task autonomous()
{
	startTask(handleMotorSlew);
	//motorRequests[leftDrive] = 127;
	//wait1Msec(2000);
	//motorRequests[leftDrive] = 0;
	//motorRequests[leftDrive] = 127
	//motorRequests[rightDrive] = 127;
	motorRequests[liftBottomLeft] = -127;
	motorRequests[liftBottomRight] = -127;
	motorRequests[liftTopLeft] = -127;
	motorRequests[liftTopRight] = -127;
	wait1Msec(1200);
	motorRequests[liftBottomLeft] = 0;
	motorRequests[liftBottomRight] = 0;
	motorRequests[liftTopLeft] = 0;
	motorRequests[liftTopRight] = 0;
	wait1Msec(500);
	motorRequests[leftDrive] = 127;
	motorRequests[rightDrive] = 127;
	wait1Msec(900);
	motorRequests[leftDrive] = 0;
	motorRequests[rightDrive] = 0;
}

task usercontrol()
{
	startTask(handleMotorSlew);
	startTask(handleLifter);
	startTask(handleFlipper);
	startTask(handleDrive);
	while (true)
	{
		wait1Msec(250);
	}
}
