#pragma config(UserModel, "./foxbot_temp_config.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#define MOTOR_COUNT 10

// Array to hold requested speed for the motors
int motorRequests[MOTOR_COUNT];

// Array to hold "slew rate" for the motors, the maximum change every time the task
// runs checking current mootor speed.
int motorSlew[MOTOR_COUNT];

task handleMotorSlew()
{
    int motorIndex;
    int motorTmp;

    // Initialize stuff
    for (motorIndex = 0; motorIndex < MOTOR_COUNT; motorIndex++)
    {
        motorRequests[motorIndex] = 0;
        motorSlew[motorIndex] = 10;
    }

    // run task until stopped
    while (true)
    {
        // run loop for every motor
        for (motorIndex = 0; motorIndex < MOTOR_COUNT; motorIndex++)
        {
            // So we don't keep accessing the internal storage
            motorTmp = motor[motorIndex];

            // Do we need to change the motor value ?
            if (motorTmp != motorRequests[motorIndex])
            {
                // increasing motor value
                if (motorRequests[motorIndex] > motorTmp)
                {
                    motorTmp += motorSlew[motorIndex];
                    // limit
                    if (motorTmp > motorRequests[motorIndex])
                        motorTmp = motorRequests[motorIndex];
                }

                // decreasing motor value
                if (motorRequests[motorIndex] < motorTmp)
                {
                    motorTmp -= motorSlew[motorIndex];
                    // limit
                    if (motorTmp < motorRequests[motorIndex])
                        motorTmp = motorRequests[motorIndex];
                }

                // finally set motor
                motor[motorIndex] = motorTmp;
            }
        }

        // Wait approx the speed of motor update over the spi bus
        wait1Msec(15);
    }
}


task handleLifter()
{
	while (true)
	{
		bool shouldLift = vexRT[Btn6U] == 1;
		bool shouldLower = vexRT[Btn6D] == 1;
		if (shouldLift)
		{
			motorRequests[liftBottomLeft] = -127;
			motorRequests[liftTopLeft] = -127;
			motorRequests[liftBottomRight] = -127;
			motorRequests[liftTopRight] = -127;
		}
		else if (shouldLower)
		{
			motorRequests[liftBottomLeft] = 127;
			motorRequests[liftTopLeft] = 127;
			motorRequests[liftBottomRight] = 127;
			motorRequests[liftTopRight] = 127;
		}
		else
		{
			motorRequests[liftBottomLeft] = 0;
			motorRequests[liftTopLeft] = 0;
			motorRequests[liftBottomRight] = 0;
			motorRequests[liftTopRight] = 0;
		}
		wait1Msec(50);
	}
}

task handleDrive()
{
	while (true)
	{
		motorRequests[leftDrive] = vexRT[Ch3];
		motorRequests[rightDrive] = vexRT[Ch2];
		wait1Msec(50);
	}
}

void pre_auton()
{
}

task autonomous()
{
	startTask(handleMotorSlew);
	//motorRequests[leftDrive] = 127;
	//wait1Msec(2000);
	//motorRequests[leftDrive] = 0;
	//motorRequests[leftDrive] = 127
	//motorRequests[rightDrive] = 127;
	motorRequests[liftBottomLeft] = -127;
	motorRequests[liftBottomRight] = -127;
	motorRequests[liftTopLeft] = -127;
	motorRequests[liftTopRight] = -127;
	wait1Msec(200);
	motorRequests[liftBottomLeft] = 0;
	motorRequests[liftBottomRight] = 0;
	motorRequests[liftTopLeft] = 0;
	motorRequests[liftTopRight] = 0;
	wait1Msec(500);
	motorRequests[leftDrive] = 127;
	motorRequests[rightDrive] = 127;
	wait1Msec(800);
	motorRequests[leftDrive] = 0;
	motorRequests[rightDrive] = 0;
	
}

task usercontrol()
{
	startTask(handleMotorSlew);
	startTask(handleLifter);
	startTask(handleDrive);
	while (true)
	{
		wait1Msec(250);
	}
}
